### ISSUE TITLE
addon fails to load subtitles

### ISSUE THREAD

**Issue by JakobDebyser** [SageTendo/mal-stremio-addon#21] opened 2024-08-29 18:04 UTC
am using the kitsu addon. also  "Alya sometimes hides her feelings in russian" is linked to "My roommate is a cat"

**Comment by SageTendo** [comment] 2024-08-31 09:36
The addon will throw that error every time, it's not actually loading subtitles. It's currently the only way of checking what is being watched, through Stremio.

Shows being incorrectly linked is likely due to the anime database having incorrect mappings from Kitsu to MAL IDs. If you'd like to have that fixed, you could talk directly to the dev of that service: https://github.com/beeequeue.

In the meantime, I'm currently working on setting up a version of the database to avoid this issue in future. Although I'm slumped with university work, I'll try my best to have it done next weekend. Sorry for the incovenience.

**Comment by SageTendo** [comment] 2024-09-02 09:57
Hi, I've tried reproducing the issue you have but it seems to match to the correct anime. Given this might be an issue with the database service, I'll close this issue.

**Closed** 2024-09-02 09:58 UTC
Labels: duplicate
